name: Mirror branch

on:
  push:
    branches: [ dev ]

jobs:
  mirror-to-nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: zofrex/mirror-branch@v1
      with:
        target-branch: nightly
